export const MINI_ACTION = 'MINI_ACTION';
export const SET_PAGE = 'SET_PAGE';
//product
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_BEGIN = 'LOAD_PRODUCTSGET_PRODUCTS_BEGIN';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const INCREASE_INDEX_IMG = ' INCREASE_INDEX_IMG';
export const DECREASE_INDEX_IMG = ' DECREASE_INDEX_IMG';
export const SET_INDEX_IMG = ' SET_INDEX_IMG';
export const SET_COLOR_INDEX = 'SET_COLOR_INDEX';
export const CLEAR_SINGLE_ACTION = 'CLEAR_SINGLE_ACTION';
export const SET_ITEM_COUNT = 'SET_ITEM_COUNT';
export const SET_ID_CART = 'SET_ID_CART';
export const RANDOM_PRODUCT = 'RANDOM_PRODUCT';
export const SET_VIEWED_PRODUCT = 'SET_VIEWED_PRODUCT';
export const UPDATE_WISHLISH = 'UPDATE_WISHLISH';
export const GET_SINGLE_PRODUCT_TSP = 'GET_SINGLE_PRODUCT_TSP,';
export const INCREASE_INDEX_IMG_TSP = '  INCREASE_INDEX_IMG_TSP,';
export const DECREASE_INDEX_IMG_TSP = '  DECREASE_INDEX_IMG_TSP,';
export const SET_INDEX_IMG_TSP = '  SET_INDEX_IMG_TSP,';
export const SET_COLOR_INDEX_TSP = '  SET_COLOR_INDEX_TSP,';
export const CLEAR_SINGLE_ACTION_TSP = '  CLEAR_SINGLE_ACTION_TSP,';
export const SET_SIZE_PRODUCT_TSP = '  SET_SIZE_PRODUCT_TSP,';
export const SET_ITEM_COUNT_TSP = '  SET_ITEM_COUNT_TSP,';
export const SET_ID_CART_TSP = '  SET_ID_CART_TSP';
export const ADD_ABOUT = 'ADD_ABOUT';
export const HIDDEN_CART_ITEM_MESS = 'HIDDEN_CART_ITEM_MESS';
export const HIDDEN_PRODUCT_ALTER_MESS_TSP = 'HIDDEN_PRODUCT_ALTER_MESS_TSP';
export const ADD_ABOUT_VIDEO = 'ADD_ABOUT_VIDEO';
//product-get home page element
export const ADD_BLOG = 'ADD_BLOG';
export const ADD_COLLECTION = 'ADD_COLLECTION';
export const SET_SIZE_PRODUCT = 'SET_SIZE_PRODUCT';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const SET_IS_IN_PRODUCT_PAGE = 'SET_IS_IN_PRODUCT_PAGE';
export const ADD_SLIDESHOW = 'ADD_SLIDESHOW';
export const ADD_BLOG_HOME = 'ADD_BLOG_HOME';
export const ADD_BANNER = 'ADD_BANNER';
//filter
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const UPDATE_SORT_OPTION = 'UPDATE_SORT_OPTION';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const UPDATE_FILTER_MENU = 'UPDATE_FILTER_MENU';
export const SET_CURRENT_MIN_PRICE = 'SET_CURRENT_MIN_PRICE';
export const SET_CURRENT_MAX_PRICE = 'SET_CURRENT_MAX_PRICE';
export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';

//cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = ' CLEAR_CART';
export const CHECK_CART = ' CHECK_CART';
export const CART_TOTAL = 'CART_TOTAL';
export const TOGGLE_ITEM_CART = 'TOGGLE_ITEM_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const HIDDEN_CART_ALTER_MESS = 'HIDDEN_CART_ALTER_MESS';
export const SHOW_CART_ALTER_MESS = 'SHOW_CART_ALTER_MESS';

//wish list
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const SET_USER = 'SET_USER';
export const UPDATE_WISHLIST = 'UPDATE_WISHLIST';
export const HIDDEN_WISHLIST_ALTER_MESS = 'HIDDEN_WISHLIST_ALTER_MESS';
export const HIDDEN_PRODUCT_ALTER_MESS = 'HIDDEN_PRODUCT_ALTER_MESS';
